r2013-02-13-moma-rails/config/routes.rb
R20130213MomaRails::Application.routes.draw do

  #created default seven routes for Artists table
  # get /artists, artists/new, artists/:id, artists/:id/edit
  # post /artists
  # put /artists, #delete /artists/:id
  #
  # see rake routes
  resources :artists, :paintings
  get '/'=>'paintings#index'

end

r2013-02-13-moma-rails/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  period      :string(255)
#  image       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :nationality, :dob, :period, :image
  has_many :paintings
end

r2013-02-13-moma-rails/app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  year       :string(255)
#  medium     :string(255)
#  style      :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#

class Painting < ActiveRecord::Base
  attr_accessible :title, :year, :medium, :style, :image, :artist_id
  belongs_to :artist    #can call a painting object, call p1.artist = an artist object
end

r2013-02-13-moma-rails/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def new
    @artist = Artist.new
  end
  def create
    artist = Artist.create(params[:artist])
    redirect_to(artist)
  end

  # creates the edit form, fills the form with parameters
  def edit
    @artist = Artist.find(params[:id])
  end

  # updates the db from the edit form
  def update
    artist = Artist.find(params[:id])
    artist.update_attributes(params[:artist])
    redirect_to(artist_path(params[:id]))
  end
  def show
    @artist = Artist.find(params[:id])
  end
  def destroy
    artist = Artist.find(params[:id])
    artist.delete
    redirect_to(artists_path)
  end
end

r2013-02-13-moma-rails/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings =Painting.all
  end
  def create
    painting = Painting.create(params['painting'])
    redirect_to(painting)
  end
  def new
    @painting = Painting.new
  end

  def edit
    @painting = Painting.find(params[:id])
    render 'new'
  end

  def update
    painting = Painting.find(params[:id])
    painting.update_attributes(params[:painting])
    redirect_to(painting)
  end
  def show
    @painting = Painting.find(params[:id])
  end
  def destroy
    painting = Painting.find(params[:id])
    painting.delete
    redirect_to(paintings_path)
  end
end

r2013-02-13-moma-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130213MomaRails</title>
  <link href='http://fonts.googleapis.com/css?family=IM+Fell+French+Canon' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class='container'>
    <h1><%= link_to "The Internet Museum of Art",paintings_path %></h1>
  <nav>
    <ul>
      <li><%= link_to "All Paintings", paintings_path, :class=>'btn' %></li>
      <li><%= link_to "All Artists", artists_path, :class=>'btn' %></li>
      <li><%= link_to "New Artist", new_artist_path, :class=>'btn' %></li>
      <li><%= link_to "New Painting", new_painting_path, :class=>'btn' %></li>
    </ul>
  </nav>
<%= yield %>
</div>

</body>
</html>