r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do

  # goes to index method in the home controller
  root :to=> 'home#index'
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :songs do
    member do
      get 'purchase'
      post 'buy'
    end
  end

  resources :albums do
    member do
      get 'purchase'
      post 'buy'
      post 'refund'
    end
  end

  resources :mixtapes do
    member do
      post 'refund'
    end
  end


  resources :genres, :albums, :artists, :songs, :mixtapes


  get '/login'    => 'session#new'
  post '/login'   => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  album_id   :integer
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :decimal(, )
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :song_ids, :genre_ids, :price
  belongs_to :album
  belongs_to :artist
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :mixtapes
  validates :price, :numericality => {:greater_than => 0}, :allow_nil => true

  # def price(purchased_songs)
  #   (songs.map(&:cost).inject(&:+)) || 0) - purchased_songs.select{|s| s.in?(songs)}.map(&:cost).inject(&+) || 0)
  # end

end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.order(:name)
  end
  def show
      @song = Song.find(params[:id])
  end
  def create
    @song = Song.create(params[:song])
    redirect_to songs_path
  end
  def edit
    @song = Song.find(params[:id])
    render :new
  end
  def new
    @song = Song.new
  end
  def update
    song = Song.find(params[:id])
    song.update_attributes(params[:song])
    redirect_to songs_path
  end
  def destroy
    song = Song.find(params[:id])
    song.delete
    redirect_to songs_path
  end

  def purchase
    @song = Song.find(params[:id])
  end

  def buy
    @song = Song.find(params[:id])
    @auth.balance -= @song.price if @auth.balance >= @song.price
    @auth.save
    params[:song][:mixtape_ids].each do |id|
      mixtape = Mixtape.find(id)
      mixtape.songs << @song
    end
    redirect_to songs_path
  end


end

r2013-02-18-tunr/app/views/songs/index.html.haml
%table
  %tr
    %td= link_to "New Song", new_song_path, :class=>'button radius tiny' if is_admin
  %tr
    %td Name
    %td Album
    %td Options
  - @songs.each do |song|
    %tr
      %td
        %div= link_to song.name, song_path(song.id)
        %em= song.artist.name if song.artist
      %td= link_to song.album.name, album_path(song.album.id) if song.album.present?
      - if @auth.present? && @auth.has_song?(song)
        %td= audio_tag(song.filename, :controls=>true)
      - else
        %td
          = link_to("Buy Now!", song_path(song.id), :class=>'button active') if !is_admin
          = link_to "Edit", edit_song_path(song.id), :class=>'button radius tiny' if is_admin
          = link_to "Delete", song, :method=>'delete', :class=>'button radius tiny',:confirm=>'Are you sure?' if is_admin

r2013-02-18-tunr/app/views/songs/new.html.haml
.eight.columns
  = render(:partial=> 'shared/errors', :locals=>{:object=>@song})
  %h2 Add a Song
  = form_for @song do |f|
    = f.label         :name
    = f.text_field    :name
    = f.label         "File Name"
    = f.text_field    :filename
    = f.label         :price
    = f.text_field    :price
    = f.label         :image
    = f.text_field    :image
    = f.submit nil, :class=>'button_radius'
    - Genre.order(:name).each do |genre|
      = check_box_tag('song[genre_ids][]',genre.id,genre.in?(@song.genres.to_a))
      %span= genre.name
.four.columns

r2013-02-18-tunr/app/views/songs/purchase.html.haml
.two.columns
.ten.columns
  %h3 Confirm Purchase
  = @song.name
  %h5= number_to_currency(@song.price)
  %h4 Add to Mixtapes
  %ul
  = form_tag buy_song_path(@song)
  - @auth.mixtapes.each do |mixtape|
    = check_box_tag('song[mixtape_ids][]',mixtape.id,@mixtape.in?(@song.mixtapes.to_a))
    %span= mixtape.name
    %br
  = button_to "Purchase", :class=>'button'

r2013-02-18-tunr/app/views/songs/show.html.haml
.one.columns
.five.columns
  %h3= @song.name
  %h4= @song.album.artists.first.name if @song.album && @song.album.artists.any?
  %h5= number_to_currency(@song.price)
  = link_to "Edit", edit_song_path(@song.id), :class=>'button radius tiny' if @auth.present? && @auth.is_admin
  = link_to "Delete", @song, :method=>'delete', :class=>'button radius tiny', :confirm=>'Are you sure you want to delete?' if is_admin

  -if @auth.present? && !@auth.is_admin
    - if !@auth.nil? && !@auth.has_song?(@song)
      %h5 Your Mixtapes
      %ul
      - @auth.mixtapes.each do |mixtape|
        %span= check_box_tag('mixtape[songs_ids][]',@song.id,@song.in?(@auth.mixtapes.to_a))
        %span= mixtape.name
        %br
      - if @auth.balance >= @song.price
        =  link_to("Buy for "+number_to_currency(@song.price), purchase_song_path, :class=>'button radius')
      - else
        .error You need more money in your account to purchase this song.
    -else
      = link_to "You Own This Song", @song, :class=>'button radius success'
      = audio_tag(@song.filename, :controls=> @auth.nil? || @auth.has_song?(@song))
  -else
    = link_to "Sign In to Buy!", login_path, :class=>'button radius success'
.three.columns
  = image_tag(@song.image, :class=>'song_image')
  %h4 Genres
  %ul
    - @song.genres.each do |genre|
      %li= link_to genre.name, genre