r2013-02-14-cookbook/config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

r2013-02-14-cookbook/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  image      :text
#  chef       :string(255)
#  cuisine    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :image, :chef, :cuisine, :recipe_ids
  has_many :recipes
end

r2013-02-14-cookbook/app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  # use when creating many-to-many relationships
  has_and_belongs_to_many :recipes
end

r2013-02-14-cookbook/app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  instructions :text
#  image        :text
#  servingssize :integer
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :instructions, :image, :servingssize, :book_id, :ingredient_ids
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

r2013-02-14-cookbook/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    book = Book.create(params[:book])
    redirect_to(books_path)
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to books_path

  end
  def edit
    @book = Book.find(params[:id])
  end
  def show
    @book = Book.find(params[:id])
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end
end

r2013-02-14-cookbook/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def new
    @ingredient = Ingredient.new
  end
  def create
  end
  def update
  end
  def edit
  end
  def show
  end
  def destroy
  end
end

r2013-02-14-cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    @recipe = Recipe.create(params[:recipe])
    redirect_to @recipe
  end
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update_attributes(params[:recipe])
    redirect_to recipe_path
  end
  def edit
    @recipe = Recipe.find(params[:id])

  end
  def show
    @recipe = Recipe.find(params[:id])

  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to recipes_path
  end
end

r2013-02-14-cookbook/app/views/recipes/edit.html.erb
<h2>Edit Recipe</h2>

<div class='form'>
<%= form_for @recipe do |f| %>
  <%= f.text_field    :name %>
  <%= f.label         :name %>

  <br>
  <%= f.text_field    :course %>
  <%= f.label         :course %>

  <br>
  <%= f.text_field       :cooktime %>
  <%= f.label         :cooktime %>

  <br>
  <%= f.text_field    :instructions %>
  <%= f.label         :instructions %>

  <br>
  <%= f.text_field    :image %>
  <%= f.label         :image %>

  <br>
  <%= f.text_field    :servingssize %>
  <%= f.label         :servingssize %>

  <br>
   <% Ingredient.order(:name).each do |ingredient| %>
    <span><%= ingredient.name %></span>
    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a)  %><br/>
  <% end %>


  <%= f.submit %>

<% end %>
</div>

r2013-02-14-cookbook/app/views/recipes/index.html.erb
<nav>
  <ul>
    <li><%= link_to "New Recipe", new_recipe_path %></li>
  </ul>
</nav>

<% @recipes.each do |recipe| %>
  <li class='listing'>
    <ul>
      <li><%= image_tag recipe.image %></li>
      <li>
        <div><%= recipe.name %></div>
        <div><%= recipe.course %></div>
        <div><%= recipe.cooktime %></div>
        <div><%= recipe.instructions %></div>
        <div><%= recipe.servingssize %></div>
        <div class='editable'>
          <%= button_to "Edit", edit_recipe_path(recipe.id), :method=>'get' %>
          <%= button_to "Delete", recipe, :method=>'delete', :confirm=>'Are you sure?' %>
        </div>
      </li>
    </ul>
  </li>


<% end %>

r2013-02-14-cookbook/app/views/recipes/new.html.erb
<h2>New Recipe</h2>

<div class='form'>
<%= form_for @recipe do |f| %>
  <%= f.text_field    :name %>
  <%= f.label         :name %>

  <br>
  <%= f.text_field    :course %>
  <%= f.label         :course %>

  <br>
  <%= f.text_field       :cooktime %>
  <%= f.label         :cooktime %>

  <br>
  <%= f.text_field    :instructions %>
  <%= f.label         :instructions %>

  <br>
  <%= f.text_field    :image %>
  <%= f.label         :image %>

  <br>
  <%= f.text_field    :servingssize %>
  <%= f.label         :servingssize %>

  <br>
   <% Ingredient.order(:name).each do |ingredient| %>
    <span><%= ingredient.name %></span>
    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a)  %><br/>
  <% end %>


  <%= f.submit %>

<% end %>
</div>

r2013-02-14-cookbook/app/views/recipes/show.html.erb
<h2>Show Recipe</h2>
<div>
  <div style='display:inline-block;'><%= image_tag @recipe.image %></div>
  <div style='display:inline-block;vertical-align:top;'>
    <div><%= @recipe.name %></div>
    <div><%= @recipe.course %></div>
    <div><%= @recipe.cooktime %></div>
    <div><%= @recipe.instructions %></div>
    <div><%= @recipe.servingssize %></div>
    <div class='editable'>
      <%= button_to "Edit", edit_recipe_path(@recipe.id), :method=>'get' %>
      <%= button_to "Delete", @recipe, :method=>'delete', :confirm=>'Are you sure?' %>
    </div>

  </div>
</div>