r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do

  # goes to index method in the home controller
  root :to=> 'home#index'
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :songs do
    member do
      get 'purchase'
      post 'buy'
    end
  end

  resources :albums do
    member do
      get 'purchase'
      post 'buy'
      post 'refund'
    end
  end

  resources :mixtapes do
    member do
      post 'refund'
    end
  end


  resources :genres, :albums, :artists, :songs, :mixtapes


  get '/login'    => 'session#new'
  post '/login'   => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/mixtape.rb
# == Schema Information
#
# Table name: mixtapes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mixtape < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user, :inverse_of => :mixtapes
  has_and_belongs_to_many :songs

end

r2013-02-18-tunr/app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  before_filter :authenticate
  def index
    @mixtapes = @auth.mixtapes
  end
  def new
    @mixtape = Mixtape.new
  end
  def create
    @mixtape = Mixtape.new(params['mixtape'])
    if @auth.mixtapes << @mixtape
      redirect_to root_path
    else
      render :new
    end
  end
  def edit
    @mixtape = Mixtape.find(params[:id])
    render :new
  end
  def update
    mixtape = Mixtape.find(params[:id])
    mixtape.update_attributes(params[:mixtape])
    redirect_to mixtapes_path
  end
  def show
    @mixtape = Mixtape.find(params[:id])
  end
  def destroy
    Mixtape.delete(params[:id])
    redirect_to mixtapes_path
  end
  def refund
    song = Song.find(params[:id])
    if mixtape.songs.include?(song)
      @auth.mixtapes.each {|mixtape|mixtape.songs.delete(@song)}
      @auth.balance += (@song.price * 0.70)
      @auth.save
    redirect_to mixtapes_path
  end

end


def authenticate
  render :new if @mixtape.nil?
end

r2013-02-18-tunr/app/views/mixtapes/index.html.haml
%h3= "Mixtapes for #{@auth.name}"
%table
  - @mixtapes.each do |mixtape|
    %tr
      %td= link_to mixtape.name, mixtape
      %td= link_to "Edit", edit_mixtape_path(mixtape.id), :class=>'button radius tiny'
      %td= link_to "Delete", mixtape, :method=>'delete', :confirm=>'Are you sure?', :class=>'button radius tiny'

r2013-02-18-tunr/app/views/mixtapes/new.html.haml
.eight.columns
  = render(:partial=>'shared/errors',:locals=>{:object=>@mixtape})
  %h2 Add Mixtape
  =form_for @mixtape do |f|
    = f.text_field :name
    = f.submit

r2013-02-18-tunr/app/views/mixtapes/show.html.haml
.twelve.columns
  %h2= @mixtape.name
  %h3 Songs
  %table
    - form_tag :method=>'post'
    - @mixtape.songs.each do |song|
      %tr
        %td= link_to song.name, song
        %td= audio_tag = audio_tag(song.filename, :controls=>true)
        %td= button_to "Refund", refund_mixtape_path(song.id), :class=>'button radius tiny', :confirm=>"You will only receive 70% of purchase value: #{song.price*0.70}. Continue?", :value=>'Sample value'